name: Example Page

on:
  push:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
        # pnpm: [8]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-setup
        with:
          node-version: ${{ matrix.node }}

      - name: Build Project
        run: pnpm build:examples

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name }}  # 动态使用分支名
          keep_files: false
          force_orphan: false
